### ISSUE TITLE
Class 'Button' not found

### ISSUE THREAD

**Issue by SigalZ** [yiisoft/yii2-bootstrap#121]
Hello,

I am learning Yii2 following their documentation.

I installed this extension but when I try to use it in a view like this:
```php
<?php
use yii\bootstrap\Html;
    use yii\widgets\ActiveForm;

    $form = ActiveForm::begin(); 
?>

<?= $form->field($model, 'name') ?>
<?= $form->field($model, 'email') ?>

<div class="form-group">
    <?= Button::widget([
        'label' => Html::icon('approve') . Html::encode('Save & apply'),
        'encodeLabel' => false,
        'options' => ['class' => 'btn-primary'],
    ]); ?>
</div>

<?php ActiveForm::end(); ?>`
```

I get this error:
Class 'Button' not found

In my folder structure I have the file: myapp/vendor/yiisoft/yii2-bootstrap/Button.php

Can you please help?

**Comment by SilverFire** [comment]
Please note, that the GitHub Issue Tracker is for bug reports and feature requests only.

We are happy to help you on the [support forum](http://www.yiiframework.com/forum/), on [IRC](http://www.yiiframework.com/chat/) (#yii on freenode), or [Gitter](https://gitter.im/yiisoft/yii2).

Please use one of the above mentioned resources to discuss the problem.
If the result of the discussion turns out that there really is a bug in the framework, feel free to
come back and provide information on how to reproduce the issue. This issue will be closed for now.

**Comment by SilverFire** [comment]
Add `use yii\bootstrap\Button;` to the beginning of your file.
Checkoutt PHP manual for the namespaces: http://php.net/manual/en/language.namespaces.php

**Comment by SigalZ** [comment]
Thank you very much.
