### ISSUE TITLE
ButtonDropDown Split with href not working as expected

### ISSUE THREAD

**Issue by tsdogs** [yiisoft/yii2-bootstrap#223]
### What steps will reproduce the problem?
create a button, enable split and add the href option

### What's expected?
as the button is split clicking on the button should open the "default" action referenced by href
Clicking on the arrow should display the dropdown list

### What do you get instead?
The dropdown list is displayed. 

### Additional info
What's the sense of having a split button if this is the behaviour of the 2 buttons is the same?

**Comment by DrLibra** [comment]
This behavior was brought by commit https://github.com/yiisoft/yii2-bootstrap/commit/9e0e3efea9c21091137a29d173936d90040be524
For a quickfix of that behavior of a dropdown button in split mode yii2-bootstrap should be locked to version 2.0.6 in composer.json (i.e. "yiisoft/yii2-bootstrap": "2.0.6" in "require" section).

**Comment by drlibra** [comment]
A source of the error is that a boostrap dropdown with splitting appears to be two buttons (instead of one button without splitting) where the first one is a simple button and the second one is a dropdown opener. A plugin registration (`$this->registerPlugin('dropdown');`) applies to the first button while it must be applied to the second one.

In a [Bootstrap docs](https://getbootstrap.com/docs/3.3/javascript/#dropdowns) it says that dropdown button can be enabled via data attributes or via JS. But in fact button is always activated by the data attributes (at least after page loading) because data attributes are required even is case of the activation by JS.

As we can completely remove the JS registration (it is a similar case as in the simple Dropdown described in https://github.com/yiisoft/yii2/issues/3749) it will solve the problem. I've created a PR.

**Comment by klimov-paul** [comment]
Resolved by commit 3ed9dcbd3d789d66ecd71fbabaedb6e7383c94c5
